name: synkuro
description: multi-platform notes app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  firebase_core: ^1.17.0
  hooks_riverpod: ^2.0.0-dev.7
  flutter_hooks: ^0.18.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
